### ISSUE TITLE
Possible memory leak on windows.

### ISSUE THREAD

**Issue by BradFitz66** [dtcristo/bevy_pixels#4] opened 2021-12-10 00:33 UTC
Noticed I had a very noticable memory leak in my program. Commented everything out except the App::build() and went my way through the systems commenting out each one until the memory leak stopped. It only stopped once .add_plugin(PixelsPlugin) was commented out.

I also tried it in a new and empty project with just the App::build() in it and still got a memory leak.

Here's a github with said empty project https://github.com/BradFitz66/Memory-Leak-Repro/

**Comment by parasyte** [comment] 2021-12-14 07:15
It's almost certainly caused by the old version of `wgpu`. Lots of memory leaks have been fixed by now. #3 should fix it.

**Comment by dtcristo** [comment] 2021-12-16 12:28
`0.2.0` includes upgrades in #3, hopefully this fixes your issues 🙏 .

**Closed as completed by dtcristo** 2021-12-16 12:28 UTC
